### PR TITLE
Footer logo placement fix

### PR DESCRIPTION
**Pull request by rmccar**
### What is the context of this PR?
Fixes: #1039 

### How to review 
Make sure footer logos are in correct positions.

### CODE REVIEW

**Comment by rmccar** [comment]
[Issue #1039 Some footer variations not rendering correctly](https://trello.com/c/tOiKTx5g/690-issue-1039-some-footer-variations-not-rendering-correctly)

**Comment by rmccar** [comment]
[Issue #1039: Some footer variations not rendering correctly](https://trello.com/c/2LEIsom3/691-issue-1039-some-footer-variations-not-rendering-correctly)

**Comment by rmccar** [comment]
[Issue #1039: Some footer variations not rendering correctly](https://trello.com/c/2LEIsom3/691-issue-1039-some-footer-variations-not-rendering-correctly)

**Review by trevorsaint — APPROVED** [review]
Great. All looks good.

**Pull request merged**
