### PR TITLE
Update address input component and addresses pattern documentation

### PR DESCRIPTION
**Pull request by jrbarnes9**
### What is the context of this PR?
- Updated address input and addresses pattern documentation and examples.
- Updated address input client-side validation error panel to remove single item list, inline with latest error panel implementation.
- Enabled any of the manual address entry fields to be wrapped in an error.

### How to review
- Check address input component and addresses pattern documentation and examples
- Check address input javascript file for error handling

### CODE REVIEW

**Comment by jrbarnes9** [comment]
[Update address pattern documentation](https://trello.com/c/A43fntFY/1246-update-address-pattern-documentation)

**Comment by jrbarnes9** [comment]
[Review address input component](https://trello.com/c/B0LuS0fr/1294-review-address-input-component)

**Review by LauraC119 — CHANGES_REQUESTED** [review]
See my separate comments about content changes to the pattern and component

**Review by rmccar — DISMISSED** [review]

**Review by LauraC119 — COMMENTED** [review]
All looks good. Just one final comment. Should the Ideal Postcodes website be on the action "check the format for a valid UK postcode" not on the name of the website? Think that's our usual accessible way to do it

**Review by rmccar — APPROVED** [review]

**Review by LauraC119 — DISMISSED** [review]

**Review by boxadesign — DISMISSED** [review]

**Review by boxadesign — APPROVED** [review]

**Review by boxadesign — DISMISSED** [review]

**Review by rmccar — DISMISSED** [review]

**Review by rmccar — DISMISSED** [review]

**Review by boxadesign — DISMISSED** [review]

**Review by boxadesign — APPROVED** [review]

**Review by JNATION85 — APPROVED** [review]

**Pull request merged**
