### PR TITLE
Add ethnic group pattern

### PR DESCRIPTION
**Pull request by rmccar**
### What is the context of this PR?
Repeat of PR #1621 which had to be reverted for more people to review the content due to the subjects sensitivity.

### How to review
- Pattern looks as it did in Census 2021 and documentation makes sense
- Content is correct and the right people have signed it off

### CODE REVIEW

**Comment by rmccar** [comment]
[Ethnic group [Ask users for...]](https://trello.com/c/9j0RLZC9/1109-ethnic-group-ask-users-for)

**Comment by rmccar** [comment]
[Ethnic group [Ask users for...]](https://trello.com/c/9j0RLZC9/1109-ethnic-group-ask-users-for)

**Review by jrbarnes9 — CHANGES_REQUESTED** [review]
Issues with examples:
- Second level questions are missing ("Which one best describes your <question 1 answer> ethnic group or background?")
- Previous links should be sentence case 
- Error summary should 'There is a problem with your answer'
- Red error panel text should be same as summary link text

screenshot


<details><summary>Browser metadata</summary>





```
Path:      /patterns/ethnic-group/
Browser:   Chrome 92.0.4515.131 on Mac OS 10.14.6
Viewport:  1920 x 978 @1x
Language:  en
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1632--ons-design-system.netlify.app%2Fpatterns%2Fethnic-group%2F&os=OS%20X&os_version=Mojave&browser=Chrome&browser_version=92.0&resolution=1920x978&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-1632--ons-design-system.netlify.app/patterns/ethnic-group/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6113b3a2642499000743b7ab&commentID=611501bfdb32edc450848e0d&resolution=resolved)

**Comment by jrbarnes9** [comment]
Discussions link url is wrong (it's linking to feedback discussion)
<details><summary>Browser metadata</summary>





```
Path:      /patterns/ethnic-group/
Browser:   Chrome 92.0.4515.131 on Mac OS 10.14.6
Viewport:  1920 x 978 @1x
Language:  en
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1632--ons-design-system.netlify.app%2Fpatterns%2Fethnic-group%2F&os=OS%20X&os_version=Mojave&browser=Chrome&browser_version=92.0&resolution=1920x978&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-1632--ons-design-system.netlify.app/patterns/ethnic-group/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6113b3a2642499000743b7ab&commentID=611501deb773bdb4b48cf678&resolution=resolved)

**Comment by jrbarnes9** [comment]
Buttons on questions usually have a top margin class of `u-mt-xl`
<details><summary>Browser metadata</summary>





```
Path:      /patterns/ethnic-group/
Browser:   Chrome 92.0.4515.131 on Mac OS 10.14.6
Viewport:  1920 x 978 @1x
Language:  en
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1632--ons-design-system.netlify.app%2Fpatterns%2Fethnic-group%2F&os=OS%20X&os_version=Mojave&browser=Chrome&browser_version=92.0&resolution=1920x978&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-1632--ons-design-system.netlify.app/patterns/ethnic-group/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6113b3a2642499000743b7ab&commentID=611502981b5fbdc5a9766d0f&resolution=resolved)

**Comment by jrbarnes9** [comment]
Typo:
> show an error message if they have not selected a required radio button or entered something ***in when it is require*** for “Other ethnic group”
<details><summary>Browser metadata</summary>





```
Path:      /patterns/ethnic-group/
Browser:   Chrome 92.0.4515.131 on Mac OS 10.14.6
Viewport:  1920 x 978 @1x
Language:  en
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1632--ons-design-system.netlify.app%2Fpatterns%2Fethnic-group%2F&os=OS%20X&os_version=Mojave&browser=Chrome&browser_version=92.0&resolution=1920x978&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-1632--ons-design-system.netlify.app/patterns/ethnic-group/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6113b3a2642499000743b7ab&commentID=611503782fe2a3a1494ce5ac&resolution=resolved)

**Comment by jrbarnes9** [comment]
Should this have a colon @LauraC119?
Screenshot 2021-08-12 at 12 18 59

**Comment by jrbarnes9** [comment]
I think we should probably show examples of all the second and third level questions so users know exactly what each question and all answers should be (laura will discuss this with you)

**Review by LauraC119 — CHANGES_REQUESTED** [review]
One change in the When to use section and the whole of How to use now needs replacing with what's on this doc: https://docs.google.com/document/d/1OccvHDCQ9TzkUmY8etdCaDpqL2GTQ8AgYfDmLyTpF_Q/edit?usp=sharing

**Comment by rmccar** [comment]
> Discussions link url is wrong (it's linking to feedback discussion)
> 
> Browser metadata
> ```
> Path:      /patterns/ethnic-group/
> Browser:   Chrome 92.0.4515.131 on Mac OS 10.14.6
> Viewport:  1920 x 978 @1x
> Language:  en
> Cookies:   Enabled
> ```
> 
> [Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1632--ons-design-system.netlify.app%2Fpatterns%2Fethnic-group%2F&os=OS%20X&os_version=Mojave&browser=Chrome&browser_version=92.0&resolution=1920x978&speed=1&start=true&ref=netlify-source)
> 
> [Open Deploy Preview](https://deploy-preview-1632--ons-design-system.netlify.app/patterns/ethnic-group/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6113b3a2642499000743b7ab&commentID=611501deb773bdb4b48cf678&resolution=resolved)

Oh yeah forgot about that, I was going to create a discussion when it was signed off, for now Ill set the link to "#"

**Comment by rmccar** [comment]
No longer publishing pattern

**Pull request closed without merging**
