### PR TITLE
Tweak header logo sizes

### LINKED ISSUE #1340: Header broken in IE11
Header broken in IE11

Traced back to PR #1036 
Screenshot 2021-01-29 at 09 25 22

_Originally posted by @jrbarnes9 in https://github.com/ONSdigital/design-system/discussions/160#discussioncomment-320086_

### PR DESCRIPTION
**Pull request by jrbarnes9**
## What is the context of this PR?
Header census logo changes

Also:
- renames xs breakpoint to xxs and xs breakpoint is at new width and updates components to work with the new breakpoints
- tidies some css
- adds new smaller nisra logo for smaller breakpoints

## How to review
- Check census header logo looks correct at all view width sizes and conforms with non census headers
- Test visual regression for global changes due to new breakpoint

Closes #1340 #1333

### CODE REVIEW

**Comment by jrbarnes9** [comment]
[#1339 Adjust census logo size at breakpoints](https://trello.com/c/zgSU2Y4Y/850-1339-adjust-census-logo-size-at-breakpoints)

**Comment by trevorsaint** [comment]
[Focus Order (A): Remove `tabIndex` from `header__logo` if `logoHref` not defined](https://trello.com/c/rYULh032/1012-focus-order-a-remove-tabindex-from-headerlogo-if-logohref-not-defined)

**Comment by trevorsaint** [comment]
[Issue #1340: Header broken in IE11](https://trello.com/c/g7rwB0Pi/1016-issue-1340-header-broken-in-ie11)

**Comment by jrbarnes9** [comment]
Negative ONS logo needs resizing to match positive version
Screenshot 2021-02-01 at 11 00 39

Top/bottom margin needs reducing under 400px too
Screenshot 2021-02-01 at 11 42 18
Should be:
Screenshot 2021-02-01 at 11 44 00

**Comment by trevorsaint** [comment]
Screenshot 2021-02-01 at 15 15 55

Screenshot 2021-02-01 at 15 16 06

Logos are the same scale now! Only change is colour.

Screenshot 2021-02-01 at 15 16 19

Screenshot 2021-02-01 at 15 16 28

Header has had the margins removed at 400px and below fixing the spacing issue.

**Review by trevorsaint — DISMISSED** [review]
Looks ok to me.

**Review by trevorsaint — APPROVED** [review]

**Pull request merged**
