### PR TITLE
Error and status pages pattern updates

### PR DESCRIPTION
**Pull request by jrbarnes9**
### What is the context of this PR?
Updated content and updated examples in error and status pages pattern, to be more accurate and consistent.

### How to review
Check the docs and examples

### CODE REVIEW

**Comment by jrbarnes9** [comment]
[Review and update DS error and status pages](https://trello.com/c/kUs5xUlL/1106-review-and-update-ds-error-and-status-pages)

**Review by LauraC119 — APPROVED** [review]
We got there in the end. Looks good to me

**Review by trevorsaint — COMMENTED** [review]
Hi @jrbarnes9 few things.

In some of the examples we have links that use the old approach of '#', can we change these to '#0' for consistency and not move the user to the top of the page.

Also, in regards time formatting in 'This service is temporarily unavailable' do we not label time like: '9am' instead of '9:00am' with the exception of say '9:30am'. I know GDS do it this way.

Other than that, nice job!

**Comment by jrbarnes9** [comment]
> Hi @jrbarnes9 few things.
> 
> In some of the examples we have links that use the old approach of '#', can we change these to '#0' for consistency and not move the user to the top of the page.
> 
> Also, in regards time formatting in 'This service is temporarily unavailable' do we not label time like: '9am' instead of '9:00am' with the exception of say '9:30am'. I know GDS do it this way.
> 
> Other than that, nice job!

Sure, will do.  @LauraC119 Can you confirm time formatting?

**Review by trevorsaint — APPROVED** [review]
Looks good to me.

**Review by LauraC119 — APPROVED** [review]
Good shout on the time format @trevorsaint 
All good now

**Pull request merged**
