### PR TITLE
Fix focus/click race condition on language dropdown

### LINKED ISSUE #285: Language dropdown focus click race condition
If you haven't focused the dropdown version and then long click, the menu will open from focusing but  it will then register the click event when the mouse is released and close the menu.

_Originally posted by @bameyrick in https://github.com/ONSdigital/design-system/issues/109#issuecomment-472906469_

### PR DESCRIPTION
**Pull request by bameyrick**
Will resolve #285

### CODE REVIEW

**Comment by bameyrick** [comment]
[ Language dropdown focus click race condition](https://trello.com/c/ebYnkymp/214-language-dropdown-focus-click-race-condition)

**Comment by boxadesign** [comment]
@bameyrick When I click each language it just seems to hide the menu and doesn't execute the link.

**Comment by bameyrick** [comment]
@boxadesign in this example thats correct, as the hrefs are just #... It should work if there were actually language links in there. I could update the example to link to the same url but with a query string lang value?

**Comment by boxadesign** [comment]
@bameyrick Yeah I think that would be good just to test that the url updates.

**Comment by bameyrick** [comment]
@boxadesign I've updated the example 👍

**Pull request merged**
