### PR TITLE
Spacing - fix tabs and metadata spacing

### PR DESCRIPTION
**Pull request by boxadesign**
### What is the context of this PR?
Adjust the spacing under links on tabs and metadata (messages pattern).

### How to review
Check the two components

### CODE REVIEW

**Comment by jrbarnes9** [comment]
Border showing on active tab

screenshot


<details><summary>Browser metadata</summary>





```
Path:      /components/tabs/
Browser:   Chrome 98.0.4758.80 on Mac OS 10.14.6
Viewport:  1280 x 698 @2x
Language:  en
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1952--ons-design-system.netlify.app%2Fcomponents%2Ftabs%2F&os=OS%20X&os_version=Mojave&browser=Chrome&browser_version=98.0&resolution=1280x698&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-1952--ons-design-system.netlify.app/components/tabs/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6201111354ee160008c0d6a3&commentID=6203daa54a1e87674e4be395&resolution=resolved)

**Review by rmccar — APPROVED** [review]
Looks good to me, I cant seem to recreate that border bug that Jon mentioned

**Comment by boxadesign** [comment]
> Looks good to me, I cant seem to recreate that border bug that Jon mentioned

@jrbarnes9 Neither can I

**Comment by kruncher** [comment]
I am unable to reproduce this issue either.

**Comment by jrbarnes9** [comment]
I'm still seeing it on Chrome v98.0.4758.102. Maybe run a percy check and see?

**Comment by jrbarnes9** [comment]
Also seeing the following rendering issues in both Chrome (90.0.4430.212) and Edge (96.0.1054.62) on Windows 10.

image (7)
image (8)

**Comment by boxadesign** [comment]
> Also seeing the following rendering issues in both Chrome (90.0.4430.212) and Edge (96.0.1054.62) on Windows 10.
> 
> image (7) image (8)

Are you zooming in your browser to see this?

**Comment by jrbarnes9** [comment]
> Are you zooming in your browser to see this?

Only for the purposes of taking the screenshot. I can still see the issue at 100%

**Comment by jrbarnes9** [comment]
> Border showing on active tab
> 
> screenshot
> 
> Browser metadata
> [Open Deploy Preview](https://deploy-preview-1952--ons-design-system.netlify.app/components/tabs/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6201111354ee160008c0d6a3&commentID=6203daa54a1e87674e4be395&resolution=resolved)

No longer seeing this in Chrome v98.0.4758.109 btw

**Review by kruncher — APPROVED** [review]
Looks good to me

**Pull request merged**
