### PR TITLE
fix: made termCol & descriptionCol optional

### PR DESCRIPTION
**Pull request by alec-hamilton-ons**
### What is the context of this PR?
#2084 

### How to review
Pull branch, remove `termCol` & `descriptionCol` from example file. Inspect in dev tools to see that no invalid classes are output.

### CODE REVIEW

**Review by rmccar — COMMENTED** [review]
Technically this isn't an issue as those two params are down as required in the macro options. So maybe we should not do this and close the issue? Might need a discussion on whether we want to make this change?

**Comment by alec-hamilton-ons** [comment]
> Technically this isn't an issue as those two params are down as required in the macro options. So maybe we should not do this and close the issue? Might need a discussion on whether we want to make this change?

I did notice this yes. My thoughts were that if for some reason they don't add the params, then it won't output anything invalid, which seems to me like a good thing (even if it is very unlikely). 

Another option would be to make the params optional.

**Comment by rmccar** [comment]
> > Technically this isn't an issue as those two params are down as required in the macro options. So maybe we should not do this and close the issue? Might need a discussion on whether we want to make this change?
> 
> I did notice this yes. My thoughts were that if for some reason they don't add the params, then it won't output anything invalid, which seems to me like a good thing (even if it is very unlikely).
> 
> Another option would be to make the params optional.

Just tested not setting them and 

> > Technically this isn't an issue as those two params are down as required in the macro options. So maybe we should not do this and close the issue? Might need a discussion on whether we want to make this change?
> 
> I did notice this yes. My thoughts were that if for some reason they don't add the params, then it won't output anything invalid, which seems to me like a good thing (even if it is very unlikely).
> 
> Another option would be to make the params optional.

Screenshot 2023-06-26 at 13 18 51

Removing these params breaks the rendering of the component. So if we were to make them optional we would need to agree on defaults. I don't think this is a change we want to make personally.

Need to avoid `&` in branch names too because it makes it more difficult to check them out

**Comment by alec-hamilton-ons** [comment]
Alright, following discussion here and seeing as the params mentioned are not optional, I am going to close this PR and ticket as the changes do not appear necessary.

**Pull request closed without merging**
