### PR TITLE
Prevent navigation links being clickable when mobile navigation is collapsed

### LINKED ISSUE #312: The mobile header nav is missing `display:none` when collapsed.  You can still click the menu links when it's collapsed.
The mobile header nav is missing `display:none` when collapsed.  You can still click the menu links when it's collapsed.

_Originally posted by @jrbarnes9 in https://github.com/ONSdigital/design-system/issues/160#issuecomment-484070748_

### PR DESCRIPTION
**Pull request by bameyrick**
Will resolve #312

### CODE REVIEW

**Comment by bameyrick** [comment]
[ The mobile header nav is missing `display:none` when collapsed.  You can still click the menu links when it's collapsed.](https://trello.com/c/WBAHFqSB/224-the-mobile-header-nav-is-missing-displaynone-when-collapsed-you-can-still-click-the-menu-links-when-its-collapsed)

**Comment by jrbarnes9** [comment]
Menu not working on Safari @bameyrick

**Comment by bameyrick** [comment]
> Menu not working on Safari @bameyrick

Which version? Working fine on MacOS  and iOS for me.

**Comment by bameyrick** [comment]
@jrbarnes9 Found the issue, polyfills weren't loading for examples so I've resolved this.

**Comment by jrbarnes9** [comment]
@bameyrick Not working for me in Safari on iPhone 7 with Browserstack.

**Comment by bameyrick** [comment]
@jrbarnes9 Should be resolved now

**Pull request merged**
