### PR TITLE
Added High Contrast Fixes for IE11 and Edge

### PR DESCRIPTION
**Pull request by trevorsaint**
I think when time allows we should revisit how **svgs** are used. If approached differently they would work better for us instead of having to hack it this way.

We also need to look at icons globally because the viewBox is causing all sorts of positioning issues. The viewBox should ideally be like the following, whole pixel values.

```
viewBox: 0 0 16 16
viewBox: 0 0 24 24
viewBox: 0 0 32 32
```

**Unfortunately we have this:**

Screenshot 2021-02-05 at 14 31 23

This is causing complicated positioning which in most cases is a battle to align.

I tend to follow this approach personally: https://material.io/design/iconography/system-icons.html#grid-and-keyline-shapes

Some of the filters are not supported in IE11 only Edge. On the plus side some things work fine in IE11 and not in Edge so things were improved for both browsers.

### Before and After visuals
Screenshot 2021-02-05 at 11 34 12

Screenshot 2021-02-05 at 11 35 08

--

Screenshot 2021-02-05 at 13 15 11

Screenshot 2021-02-05 at 13 14 46

--

Screenshot 2021-02-05 at 12 49 40

Screenshot 2021-02-05 at 12 49 18

--

Screenshot 2021-02-05 at 13 19 27

Screenshot 2021-02-05 at 13 19 04

--

Screenshot 2021-02-05 at 13 09 36

Screenshot 2021-02-05 at 13 09 45

--

Screenshot 2021-02-05 at 12 43 29

Screenshot 2021-02-05 at 12 43 15

--

Screenshot 2021-02-05 at 13 29 28

Screenshot 2021-02-05 at 13 29 05

--

Screenshot 2021-02-05 at 12 37 53

Screenshot 2021-02-05 at 12 38 06

--

Screenshot 2021-02-05 at 13 36 19

--

Screenshot 2021-02-05 at 13 08 56

### CODE REVIEW

**Comment by boxadesign** [comment]
Tested High Contrast Mode on Edge on Windows 10 (Microsoft Surface Go) and looks good.

**Review by boxadesign — APPROVED** [review]

**Comment by jrbarnes9** [comment]
Should the accordions be link colour (yellow)? Their normal appearance was styled to match links after DAC Dragon user had trouble selecting them
Screenshot 2021-02-08 at 09 54 52

**Comment by jrbarnes9** [comment]
Autosuggest focus state missing from results list

Screenshot 2021-02-08 at 10 01 19
Screenshot 2021-02-08 at 10 01 30

**Comment by jrbarnes9** [comment]
IE11 - Breadcrumbs icons not visible

Screenshot 2021-02-08 at 10 04 30

**Comment by trevorsaint** [comment]
> IE11 - Should the accordions be link colour (yellow)? Their normal appearance was styled to match links after DAC Dragon user had trouble selecting them. They have `role=link` for this reason
> Screenshot 2021-02-08 at 09 54 52

I think this is based on visited or non visited links.

**Comment by trevorsaint** [comment]
> IE11 - Breadcrumbs icons not visible
> 
> Screenshot 2021-02-08 at 10 04 30

Must have missed this one. Let me add that in now.

**Comment by jrbarnes9** [comment]
[Radio Buttons (Usability): Important information including the visual indication a checked radio not visible in alternative colour schemes](https://trello.com/c/kf1c8X2C/927-radio-buttons-usability-important-information-including-the-visual-indication-a-checked-radio-not-visible-in-alternative-colour)

**Comment by jrbarnes9** [comment]
IE11 
Screenshot 2021-02-08 at 10 17 03

**Comment by jrbarnes9** [comment]
IE11 - Lock icon not visible

Screenshot 2021-02-08 at 10 23 43

**Comment by jrbarnes9** [comment]
IE11 - SM icons not visible

**Comment by trevorsaint** [comment]
> IE11
> Screenshot 2021-02-08 at 10 17 03

This one can’t be fixed for IE11 due to the way the SVG was added into the page using an img tag. Changing this at some point would resolve this issue.

**Comment by trevorsaint** [comment]
> IE11 - SM icons not visible
> Screenshot 2021-02-08 at 10 26 11

This has been fixed for IE11.

**Comment by trevorsaint** [comment]
> IE11 - SM icons not visible
> Screenshot 2021-02-08 at 10 26 11

This has been fixed for IE11.

**Comment by trevorsaint** [comment]
> IE11 - Lock icon not visible
> 
> Screenshot 2021-02-08 at 10 23 43

This has been fixed for IE11.

**Comment by trevorsaint** [comment]
> IE11 - Autosuggest focus state missing from results list
> 
> Screenshot 2021-02-08 at 10 01 19
> Screenshot 2021-02-08 at 10 01 30

I have sorted this out with a slight indent and text underline.

Screenshot 2021-02-08 at 11 22 22

**Review by jrbarnes9 — APPROVED** [review]

**Pull request merged**
