### PR TITLE
Align Collapsible chevron with edge of page

### PR DESCRIPTION
**Pull request by rmccar**
### What is the context of this PR?
Fixes: #990 

### How to review 
Check chevron aligns with left side of page

### CODE REVIEW

**Comment by rmccar** [comment]
[Issue #990: Collapsible chevron doesn't left align with other page elements when collapsed](https://trello.com/c/7kLVCY6p/662-issue-990-collapsible-chevron-doesnt-left-align-with-other-page-elements-when-collapsed)

**Comment by boxadesign** [comment]
Issue with active state spacing...

image

image

**Comment by rmccar** [comment]
> Issue with active state spacing...
> 
> image
> 
> image

Yeah so I've spoken with @jrbarnes9 about this. The closed state needed to be aligned with the side of the page but that would mean that the chevron on the open state would creep outside of the focus highlighting and wouldn't be aligned with the side of the page. The other solution would be for the text to move to the right when opening to keep that spacing but I think that would look odd. The spacing is a bit tight though when it is open. We could make the icon smaller when open is another option? But that would be odd too.

**Comment by boxadesign** [comment]
Couldn't the close state have the same spacing as bulleted lists...

image

**Review by boxadesign — APPROVED** [review]

**Pull request merged**
