### PR TITLE
Updated hero component to allow for website redirect link

### PR DESCRIPTION
**Pull request by jrbarnes9**
### What is the context of this PR?
- A new line and link is required at the bottom of the hero to place a redirect to Nisra census website for NI residents.
- The hero image/graphics need to be smaller on mobile to bring up the content and CTAs above the fold

### How to review 
- Check all hero variants at all breakpoints

### CODE REVIEW

**Review by trevorsaint — APPROVED** [review]
Looks good to me Jon.

**Comment by rmccar** [comment]
Might want to adjust the breakpoints slightly on the default hero. Just looks a bit weird to me that between widths 771 and 740 the line "Design and build digital services for the ONS" wraps to 3 lines and then back onto 2 when you make the window smaller. Only a small thing. Other than that looks good

**Comment by jrbarnes9** [comment]
[Update hero component to allow for website redirect link and pull up CTAs on mobile](https://trello.com/c/U8S9gDCS/1037-update-hero-component-to-allow-for-website-redirect-link-and-pull-up-ctas-on-mobile)

**Review by boxadesign — DISMISSED** [review]

**Comment by jrbarnes9** [comment]
> Might want to adjust the breakpoints slightly on the default hero. Just looks a bit weird to me that between widths 771 and 740 the line "Design and build digital services for the ONS" wraps to 3 lines and then back onto 2 when you make the window smaller. Only a small thing. Other than that looks good

That's just where the grid is changing from 8 col to 12

**Review by rmccar — DISMISSED** [review]

**Review by boxadesign — DISMISSED** [review]

**Review by boxadesign — APPROVED** [review]
Checked the netlify output. Looks good

**Review by rmccar — APPROVED** [review]

**Pull request merged**
