### PR TITLE
Fix/3055/add padding between checkbox list and label

### PR DESCRIPTION
**Pull request by balibirchlee**
### What is the context of this PR?

Aligns padding of checkbox label with other text - rather than 'adding' padding, I actually removed the padding css that was specifically reducing the padding of checkbox labels.

The VR tests are passing locally but failing here - I think a github issue not a code issue.

Fixes: https://github.com/ONSdigital/design-system/issues/3055

### How to review this PR

You can see the difference on the checkboxes pages.

### Checklist

This needs to be completed by the person raising the PR.

- [x] I have selected the correct Assignee
- [x] I have linked the correct Issue

### CODE REVIEW

**Review by rmccar — CHANGES_REQUESTED** [review]
I think the margin after the "or" is now missing on mutually exclusive options
Screenshot 2024-03-11 at 15 42 14

**Review by alessioventuriniAND — CHANGES_REQUESTED** [review]
Same as Richard's comment. Once you fix that I am happy to approve too :)

**Comment by adi-unni** [comment]
Happy to approve code-wise but might need to get Dina's approval too.

**Review by adi-unni — APPROVED** [review]

**Review by rmccar — CHANGES_REQUESTED** [review]
Like Adi mentioned this seems to have had some potential unintended changes. Needs to be checked with Dina. To me the "Select all that apply" looks a bit far away now but see what she says.

**Comment by balibirchlee** [comment]
@adi-unni @rmccar 

Dina confirmed she's happy with the all the visual changes!

**Review by rmccar — APPROVED** [review]

**Review by alessioventuriniAND — APPROVED** [review]

**Pull request merged**
