### PR TITLE
Fix accordions on small breakpoints

### PR DESCRIPTION
**Pull request by rmccar**
### What is the context of this PR?
Fixes: #1148 

### How to review 
Check Accordions look right on small breakpoints

### CODE REVIEW

**Comment by rmccar** [comment]
[Issue #1148: Accordions alignment broken on small breakpoint](https://trello.com/c/EzsfHfv6/768-issue-1148-accordions-alignment-broken-on-small-breakpoint)

**Comment by rmccar** [comment]
[Issue #1148: Accordions alignment broken on small breakpoint](https://trello.com/c/wSKvD45w/769-issue-1148-accordions-alignment-broken-on-small-breakpoint)

**Comment by boxadesign** [comment]
Accordions look ok but something has happened with the list change you made. The margin was to be removed on icon lists only I believe 
image

**Comment by rmccar** [comment]
> Accordions look ok but something has happened with the list change you made. The margin was to be removed on icon lists only I believe
> image

Ive just fixed this in #1151

**Review by boxadesign — APPROVED** [review]

**Pull request merged**
