### PR TITLE
Summary: Allow for 3 levels of headings

### PR DESCRIPTION
**Pull request by rmccar**
This PR is to add another title level for summaries. A group title has been added with a H2 tag. If the group title does exist then the title field will become a H3 tag

### CODE REVIEW

**Comment by rmccar** [comment]
[Summary: Allow for 3 levels of headings](https://trello.com/c/2cWCMB2l/470-summary-allow-for-3-levels-of-headings)

**Comment by rmccar** [comment]
[Improve readability of summaries for large sections (S)](https://trello.com/c/1nVbtipX/3607-improve-readability-of-summaries-for-large-sections-s)

**Comment by ajmaddaford** [comment]
The spacing between the headings doesn't look quite right:
image
For example "Staff" appears to be closer to the previous answer than the answers associated with the heading.

**Comment by jrbarnes9** [comment]
Hub status is lost on mobile view...

Screenshot 2020-02-07 at 09 20 04
Screenshot 2020-02-07 at 09 19 58

**Pull request merged**
