### PR TITLE
 Exploring Unnecessary Conditionals: Mutually-Exclusive

### PR DESCRIPTION
**Pull request by SriHV**
### What is the context of this PR?
#3025 .... Added new params that were missing in `_macro_options.md` 

### How to review this PR
Check that params mentioned in examples are present in readme

### Checklist

This needs to be completed by the person raising the PR.

- [x] I have selected the correct Assignee
- [x] I have linked the correct Issue

### CODE REVIEW

**Review by rmccar — CHANGES_REQUESTED** [review]
I think you need to rebase your branch, you've pulled in a few commits from other PRs. Also a lot of these arent ones we want to add in. Some of these are covered with the `exclusiveOptions` param and others arent used within this macro. The thing with this component is that its used within other components and not really used on its own like others are

**Comment by SriHV** [comment]
> I think you need to rebase your branch, you've pulled in a few commits from other PRs. Also a lot of these arent ones we want to add in. Some of these are covered with the `exclusiveOptions` param and others arent used within this macro. The thing with this component is that its used within other components and not really used on its own like others are

okay, got it, I can close this PR if all of them added are not necessary actually.

**Comment by rmccar** [comment]
> > I think you need to rebase your branch, you've pulled in a few commits from other PRs. Also a lot of these arent ones we want to add in. Some of these are covered with the `exclusiveOptions` param and others arent used within this macro. The thing with this component is that its used within other components and not really used on its own like others are
> 
> okay, got it, I can close this PR if all of them added are not necessary actually.

From what I can see:
- `deselectCheckboxAdjective` needs adding
- `deselectCheckboxAdjective` needs removing
- the fieldset ones need adding

If you want to do this easily without messing about rebasing you could pull the latest main and start a new branch, thats probably what I would do in this instance.

**Comment by SriHV** [comment]
> > > I think you need to rebase your branch, you've pulled in a few commits from other PRs. Also a lot of these arent ones we want to add in. Some of these are covered with the `exclusiveOptions` param and others arent used within this macro. The thing with this component is that its used within other components and not really used on its own like others are
> > 
> > 
> > okay, got it, I can close this PR if all of them added are not necessary actually.
> 
> From what I can see:
> 
> * `deselectCheckboxAdjective` needs adding
> * `deselectCheckboxAdjective` needs removing
> * the fieldset ones need adding
> 
> If you want to do this easily without messing about rebasing you could pull the latest main and start a new branch, thats probably what I would do in this instance.

I will do that actually, thanks!

**Comment by SriHV** [comment]
Closing this due to rebase issues

**Pull request closed without merging**
