### PR TITLE
Document how to install the proto kit

### PR DESCRIPTION
**Pull request by jrbarnes9**
### What is the context of this PR?
Guidance to help designers install the proto kit.

Also...
- Added some synonyms to the highlight pattern page
- Change minChars to 2, to speed up site search

### How to review
- Follow guidance doc ensuring all steps are accurate and complete.
- Check site search is quicker and highlight page can be found using synonyms

### CODE REVIEW

**Comment by jrbarnes9** [comment]
[Document installing the SDC prototype kit](https://trello.com/c/xtjjaejl/1334-document-installing-the-sdc-prototype-kit)

**Comment by boxadesign** [comment]
Looks good. Might be worth putting in a line at the end to see the readme for further instructions or state that you need to run `yarn install` and `yarn start` to run the app.

**Comment by jrbarnes9** [comment]
> Looks good. Might be worth putting in a line at the end to see the readme for further instructions or state that you need to run `yarn install` and `yarn start` to run the app.

I'll just add a link, to keep all the 'using' guidance separate from the installation stuff, while we figure out where we'll publish it.

**Review by boxadesign — DISMISSED** [review]

**Review by rmccar — COMMENTED** [review]
Looks good but I thought having the screenshots in collapsibles was a bit odd

**Review by kruncher — APPROVED** [review]
This looks good to me.

**Comment by jrbarnes9** [comment]
Moving to the proto kit repo, to be documented there.

**Pull request closed without merging**
