### PR TITLE
Add functionality to exclude examples from VR tests

### PR DESCRIPTION
**Pull request by adi-unni**
### What is the context of this PR?

Fixes: #3116

Previously the sticky components would be failing the VR tests repeatedly. Looking at the backstop JS artifacts showed that the example was not being fully rendered and no fix was found to prevent this. The decision was made to stop certain examples from being included. I have added a change where you can edit the contents of the exclude list to remove certain examples from the VR tests.

Important note: If you are making a change to Table of Contents or a change to any global CSS. you must also check the ToC stick components separately. 

### How to review this PR

Check that the VR tests no longer run on example-table-of-contents-sticky and example-table-of-contents-sticky-full-page examples. Also sense check the code and please give suggestions if you have any enhancements.

### Checklist

This needs to be completed by the person raising the PR.

- [x] I have selected the correct Assignee
- [x] I have linked the correct Issue

### CODE REVIEW

**Review by balibirchlee — APPROVED** [review]

**Review by alessioventuriniAND — APPROVED** [review]
You might want to update the reference files and push to git lfs too.

**Review by alessioventuriniAND — APPROVED** [review]

**Review by rmccar — CHANGES_REQUESTED** [review]
Isn't there a better way of fixing this? I don't like removing examples from tests. I can see you've added warning comments to the affected files but I can see this still getting forgotten. It will be very easy to forget to check this when changing global css. If we haven't already I think we need to look into why the examples aren't being rendered correctly, is it a race condition?

**Comment by adi-unni** [comment]
> Isn't there a better way of fixing this? I don't like removing examples from tests. I can see you've added warning comments to the affected files but I can see this still getting forgotten. It will be very easy to forget to check this when changing global css. If we haven't already I think we need to look into why the examples aren't being rendered correctly, is it a race condition?

Alessio had looked into fixing this issue for a week in Feb and tried multiple different solutions with no result. I'll give it a try today, but if I can't, then this will be a temporary fix to prevent other PRs from being blocked while I work on a solution that separates CI tests from local tests so that all local tests run but omits tests in CI.

**Comment by rmccar** [comment]
> > Isn't there a better way of fixing this? I don't like removing examples from tests. I can see you've added warning comments to the affected files but I can see this still getting forgotten. It will be very easy to forget to check this when changing global css. If we haven't already I think we need to look into why the examples aren't being rendered correctly, is it a race condition?
> 
> Alessio had looked into fixing this issue for a week in Feb and tried multiple different solutions with no result. I'll give it a try today, but if I can't, then this will be a temporary fix to prevent other PRs from being blocked while I work on a solution that separates CI tests from local tests so that all local tests run but omits tests in CI.

I still don't think removing test coverage is the answer, which includes removing tests in CI. There must be another way to fix this

**Pull request closed without merging**
