### PR TITLE
Remove Feedback from pageConfig

### PR DESCRIPTION
**Pull request by rmccar**
### What is the context of this PR?
Remove new Feedback component from being set in pageConfig

This will be a **BREAKING CHANGE** because now feedback cant be set using pageConfig.

### How to review 
Check that Feedback component still looks and works as it should without setting it on pageConfig

### CODE REVIEW

**Comment by rmccar** [comment]
[Move feedback out of pageConfig](https://trello.com/c/VJ1Ff6Pk/735-move-feedback-out-of-pageconfig)

**Review by jrbarnes9 — COMMENTED** [review]
Need to remove it from the pageConfig table at /styles/page-template/

**Review by boxadesign — DISMISSED** [review]

**Comment by jrbarnes9** [comment]
I can't see the feedback pattern in this PR?

**Comment by rmccar** [comment]
> I can't see the feedback pattern in this PR?

Sorted, the feedback index.njk got moved into examples somehow

**Review by jrbarnes9 — APPROVED** [review]

**Pull request merged**
