### PR TITLE
Reduce top padding on links after summary

### PR DESCRIPTION
**Pull request by rmccar**
### What is the context of this PR?
Fixes: #1128 

### How to review 
Check padding is now correct

### CODE REVIEW

**Comment by rmccar** [comment]
[Issue #1128: Reduce top padding on the link container that follows a summary](https://trello.com/c/BqepVICM/755-issue-1128-reduce-top-padding-on-the-link-container-that-follows-a-summary)

**Review by jrbarnes9 — COMMENTED** [review]
If you add `margin-bottom: -1px;` to `summary` css, we can avoid the double-border when there's only row in the summary

**Comment by rmccar** [comment]
> margin-bottom: -1px;

I was going to add that to the summary PR but yeah ill add it here

**Comment by jrbarnes9** [comment]
> > margin-bottom: -1px;
> 
> I was going to add that to the summary PR but yeah ill add it here

Is it possible to add this only if there is only 1 in the loop?

**Comment by rmccar** [comment]
> > > margin-bottom: -1px;
> > 
> > 
> > I was going to add that to the summary PR but yeah ill add it here
> 
> Is it possible to add this only if there is only 1 in the loop?

Yeah should be able to do that

**Comment by rmccar** [comment]
> > > margin-bottom: -1px;
> > 
> > 
> > I was going to add that to the summary PR but yeah ill add it here
> 
> Is it possible to add this only if there is only 1 in the loop?

Did look at doing this but the border needed to be adjusted on the parent and not the item itself

**Review by boxadesign — APPROVED** [review]

**Pull request merged**
