### PR TITLE
Added underline thickness to link hover state

### PR DESCRIPTION
**Pull request by boxadesign**
### What is the context of this PR?
Addresses https://github.com/ONSdigital/design-system/issues/1261

### How to review 
Ensure that the global link hover state doesn't have any unwanted effects on links in components.

### CODE REVIEW

**Review by armstrongb — DISMISSED** [review]
A few oddities about the place from this one.

### 1. Tabs 
- underline coloured but text not.
tabs-link-colour

### 2. Tables (sortable)
- The underline on the sortable headers doesn't get thicker.

### 3. Promotional banner with image
- inline link the underline vanishes and no colour change is apparent on the link. 

### 4. Hero (Campaign happening now) & Collapsible & Accordion
- accordion/collapsible link underline vanishes but content of accordion the links behave as expected.

### 5. Footer
- underline vanishes on all footer links
- (Crest (no OGL - Cymraeg) - 'swyddi' should be 'Swyddi'

### 6. Download
- Bold links underline jumps upward on hover (Chrome Version 87.0.4280.88 OSX)
single-download-link-jump

### 7. Card
- Card bold link jumps upwards on hover (Chrome Version 87.0.4280.88 OSX)
card-link-jump

### 8. Breadcrumb & Back links
- link underline vanishes instead.

### 9. Articles
- heading as link, underline jumps on hover (Chrome Version 87.0.4280.88 OSX)

**Comment by boxadesign** [comment]
> A few oddities about the place from this one.
> 
> ### 1. Tabs
> * underline coloured but text not.
> 
> tabs-link-colour
> 
> ### 2. Tables (sortable)
> * The underline on the sortable headers doesn't get thicker.
> 
> ### 3. Promotional banner with image
> * inline link the underline vanishes and no colour change is apparent on the link.
> 
> ### 4. Hero (Campaign happening now) & Collapsible & Accordion
> * accordion/collapsible link underline vanishes but content of accordion the links behave as expected.
> 
> ### 5. Footer
> * underline vanishes on all footer links
> * (Crest (no OGL - Cymraeg) - 'swyddi' should be 'Swyddi'
> 
> ### 6. Download
> * Bold links underline jumps upward on hover (Chrome Version 87.0.4280.88 OSX)
>   single-download-link-jump
> 
> ### 7. Card
> * Card bold link jumps upwards on hover (Chrome Version 87.0.4280.88 OSX)
>   card-link-jump
> 
> ### 8. Breadcrumb & Back links
> * link underline vanishes instead.
> 
> ### 9. Articles
> * heading as link, underline jumps on hover (Chrome Version 87.0.4280.88 OSX)

Have addressed the issues you observed. I have also brought into scope some things that were not originally in scope but you had spotted i.e. breadcrumbs, footer links.

**Comment by jrbarnes9** [comment]
Collapsibles also need a thicker underline on hover

**Comment by jrbarnes9** [comment]
card-link-jump

...this issue still exists on cards with images

**Comment by jrbarnes9** [comment]
Missing from reset filters link
https://deploy-preview-1275--ons-design-system.netlify.app/patterns/download-resources/

**Comment by jrbarnes9** [comment]
Adding too much thickness on messages links.  Because they're links within an `h3`

**Comment by jrbarnes9** [comment]
Missing from Pager pagination: https://deploy-preview-1275--ons-design-system.netlify.app/components/content-pagination/examples/content-pagination/

**Comment by rmccar** [comment]
All looks good but I think we need to add a hover state to "skip to content" and the DS example tabs
image

**Review by jrbarnes9 — APPROVED** [review]

**Review by rmccar — APPROVED** [review]

**Pull request merged**
