### PR TITLE
Added clearfix for icon lists

### PR DESCRIPTION
**Pull request by boxadesign**
### What is the context of this PR?
Fixes https://github.com/ONSdigital/design-system/issues/1094

### CODE REVIEW

**Review by trevorsaint — CHANGES_REQUESTED** [review]
Hi @boxadesign could we not add the clearfix to the `.list__item` class rather than a utility class?

We also need a vertical align on the `.list__link` even if for social icons to ensure text sits in the middle.

Social icons should be using the xl scale. In the design they are 2rem (36px), so we may need an xxl.

**Comment by boxadesign** [comment]
> Hi @boxadesign could we not add the clearfix to the `.list__item` class rather than a utility class?
> 
> We also need a vertical align on the `.list__link` even if for social icons to ensure text sits in the middle.
> 
> Social icons should be using the xl scale. In the design they are 2rem (36px), so we may need an xxl.

I think i'll just introduce flex box. This was a quick fix tbh.

**Review by trevorsaint — CHANGES_REQUESTED** [review]
Hi Matt sorry to be a pain.

You will need to apply the same flex approach for the `inline--list`. We have an inline list version of the social icons and applying this class causes alignment issues.

In your PR
Screenshot 2020-10-28 at 12 10 59

With inline-flex applied to the`list__item`.
Screenshot 2020-10-28 at 12 11 18

Very subtle agreed, but this would ensure the text is vertically aligned.

**Comment by boxadesign** [comment]
> Hi Matt sorry to be a pain.
> 
> You will need to apply the same flex approach for the `inline--list`. We have an inline list version of the social icons and applying this class causes alignment issues.
> 
> In your PR
> Screenshot 2020-10-28 at 12 10 59
> 
> With inline-flex applied to the`list__item`.
> Screenshot 2020-10-28 at 12 11 18
> 
> Very subtle agreed, but this would ensure the text is vertically aligned.

No problem Trevor. Do we have that as an example in the DS anywhere?

**Comment by trevorsaint** [comment]
> > Hi Matt sorry to be a pain.
> > You will need to apply the same flex approach for the `inline--list`. We have an inline list version of the social icons and applying this class causes alignment issues.
> > In your PR
> > Screenshot 2020-10-28 at 12 10 59
> > With inline-flex applied to the`list__item`.
> > Screenshot 2020-10-28 at 12 11 18
> > Very subtle agreed, but this would ensure the text is vertically aligned.
> 
> No problem Trevor. Do we have that as an example in the DS anywhere?

We don’t have an example of use in the design system,  however it will be used on the Census2021 website. 

**For example:** 
https://deploy-preview-118--sdc-prototypes.netlify.app/prototypes/census-website-engage/home/
https://deploy-preview-118--sdc-prototypes.netlify.app/prototypes/census-website-engage/ni/home/

**Review by jrbarnes9 — APPROVED** [review]

**Review by trevorsaint — CHANGES_REQUESTED** [review]
Me again and sorry.

**In an inline use case:** we have margin bottom on both the li’s and the ul totalling 36px bottom margin. I don’t think this should be added by default. I would expect that to be added as utility classes if required. (in my case not).

For some reason we also have margin right on each link, so obviously the gap between each item inline is more than double what it needs to be.

**How it should render**
Screenshot 2020-10-30 at 15 11 30

**Review by trevorsaint — CHANGES_REQUESTED** [review]
Unfortunately on small devices, it does not have sufficient spacing. See example:

Screenshot 2020-11-03 at 13 29 53

**Review by trevorsaint — APPROVED** [review]
Great Rich. Looks good.

**Pull request merged**
