### PR TITLE
Moved the date input component to a pattern and updated guidance

### PR DESCRIPTION
**Pull request by jrbarnes9**

### CODE REVIEW

**Comment by jrbarnes9** [comment]
[Dates](https://trello.com/c/aLDI1yLx/134-dates)

**Comment by bameyrick** [comment]
Could you also update the design forum issue to be pattern rather than component as part of this too please?

**Comment by jrbarnes9** [comment]
> Could you also update the design forum issue to be pattern rather than component as part of this too please?

Think I did?

**Comment by bameyrick** [comment]
Oh yes you did.... I was too lazy to actually check...

**Pull request merged**
