### PR TITLE
Replace highlight with prismjs

### PR DESCRIPTION
**Pull request by rmccar**
### What is the context of this PR?
Due to the security issue in highlightjs v9. I investigated into upgrading to v10 but v10 doesnt support ie11. So this PR is to replace highlightjs with prismjs which does support ie11.

As part of this I needed to rename the `tag` css class used in the find a support centre pattern

### How to review 
- Check that code blocks in example tabs look correct and code is styled
- Check that find a support centre pattern still looks as it should

### CODE REVIEW

**Comment by rmccar** [comment]
[Replace highlightjs with prismjs](https://trello.com/c/JBxkI38T/889-replace-highlightjs-with-prismjs)

**Comment by boxadesign** [comment]
@rmccar Looks like it all works now. I'd maybe switch the font to monospace.

**Comment by rmccar** [comment]
> @rmccar Looks like it all works now. I'd maybe switch the font to monospace.

I think it is a monospace font its using the font family `Consolas,Monaco,Andale Mono,Ubuntu Mono,monospace`

**Review by boxadesign — APPROVED** [review]

**Comment by jrbarnes9** [comment]
[Replace highlightjs with prismjs](https://trello.com/c/JBxkI38T/889-replace-highlightjs-with-prismjs)

**Pull request merged**
