### PR TITLE
Change grey 3

### PR DESCRIPTION
**Pull request by rmccar**
### What is the context of this PR?
Fixes: #1027 and #1026 

### How to review 
- Check grey 3 looks correct
- Check grey on:
  - Collapsiable
  - Doanloads
  - Download resources 
  - Sortable Table
  - Paternlib example
  - Footer hr

### CODE REVIEW

**Comment by rmccar** [comment]
[Issue #1026: `footer__hr` is too dark.  Suggest using a new `$color-grey-3` (`#ACACAC`)](https://trello.com/c/FyiPgDcK/682-issue-1026-footerhr-is-too-dark-suggest-using-a-new-color-grey-3-acacac)

**Comment by rmccar** [comment]
[Issue #1027: `$color-grey-4` is too close to `$color-grey-3` in level of lightness.](https://trello.com/c/EqxxUpdD/681-issue-1027-color-grey-4-is-too-close-to-color-grey-3-in-level-of-lightness)

**Review by trevorsaint — DISMISSED** [review]
Looks good.

**Review by jrbarnes9 — DISMISSED** [review]

**Review by trevorsaint — APPROVED** [review]
This all looks good to me.

**Pull request merged**
